title: Mobile Robotics Project
description: ROS 2 Autonomous Mobile Robotics Project
theme: just-the-docs

url: https://varad1722.github.io
baseurl: /Mobile_Robotics

remote_theme: just-the-docs/just-the-docs
math: mathjax
